apiVersion: v1
kind: Pod
metadata:
  name: pod-in-net1 
  annotations:
    mizar.com/vpc: vpc1 
    mizar.com/subnet: net1 
spec:
  containers:
  - name: vanilla-container
    image: mizarnet/testpod:latest 
  nodeName: ip-172-31-11-12
